####
# Copyright (c) 2014-2015 BTCPayServer
#
# Example config using a yml file
#
btcpayserver:
    network: testnet
    public_key: /tmp/btcpayserver.pub
    private_key: /tmp/btcpayserver.pri
    key_storage_password: YourTopSecretPassword
